# Seed file generated by DataSender
# Generated at 2024-10-01 14:02:09 +0200

person = Person.find_or_create_by!(client_user_id: '123') do |p|
  p.client_timestamp = '2023-10-25T23:48:46+00:00'
  p.account_id = 'XXXXX'
end

trait = Trait.find_or_create_by!(name: 'firstName', account_id: person.account_id, value_type: 'text')
trait.client_applications << ClientApplication.find_by!(application_id: '94948')
TraitValue.create!(trait_id: trait.id, person_id: person.id, data: 'John')

trait = Trait.find_or_create_by!(name: 'lastName', account_id: person.account_id, value_type: 'text')
trait.client_applications << ClientApplication.find_by!(application_id: '94948')
TraitValue.create!(trait_id: trait.id, person_id: person.id, data: 'Doe')

