# Seed file generated by DataSender
# Generated at 2024-10-01 13:58:20 +0200

person = Person.find_or_create_by!(client_user_id: '123') do |p|
  p.client_timestamp = ''
  p.account_id = 'XXXXX'
end

trait = Trait.find_or_create_by!(name: 'firstName', account_id: person.account_id, value_type: 'text')
